export enum PERFILUSUARIO {
    CLIENTE = 'CLIENTE',//SOLO VERA COSAS DEL CLIENTE
    EMPLEADOA = 'EMPLEADOA',//EMPLEADO ADMINISTRADOR PUEDE VER TODO
    EMPLEADON = 'EMPLEADON',//EMPLEADO NORMAL SOLO PUEDE VER LO QUE TIENE ASIGNADO
    


}