export enum ESTATUSRECOLECCION {
    CREADA='CREADA',
    RECOLECTADA='RECOLECTADA',
    ENRUTA='EN_RUTA',
    ENTREGADA='ENTREGADA',
    NORECIBIDA='NO_RECIBIDA'
   
}
export enum ESTATUS_CABECERA_RECOLECCION {
    CREADA='CREADA',
    RECOLECTADA='RECOLECTADA',
    ANULADA='ANULADA',
    NORECOLECTADA='NORECOLECTADA'
   
}

