export enum ESTATUSRECOLECCION {
    CREADA='CREADA',
    RECOLECTADA='RECOLECTADA',
    ENRUTA='EN RUTA',
    ENTREGADA='ENTREGADA',
    NORECIBIDA='NO RECIBIDA'
   
}
export enum ESTATUS_CABECERA_RECOLECCION {
    CREADA='CREADA',
    RECOLECTADA='RECOLECTADA',
    ANULADA='ANULADA',
    NORECOLECTADA='NORECOLECTADA'
   
}

